# Generated by Django 5.2.7 on 2025-11-13 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("playing", "Playing"),
                            ("ended", "Ended"),
                        ],
                        default="ready",
                        max_length=20,
                    ),
                ),
                ("settings", models.JSONField(default=dict)),
                ("field", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "turn_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_they_play",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GamePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="Turn order (0=first, 1=second, etc.)"
                    ),
                ),
                (
                    "scout_revealed_coords",
                    models.JSONField(
                        default=list,
                        help_text="List of coordinates revealed by scout actions this turn, format: [[x1, y1], [x2, y2], ...]",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="game.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["game", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game", "order"), name="unique_game_order"
                    )
                ],
                "unique_together": {("game", "player")},
            },
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField(help_text="Move payload from client")),
                (
                    "client_seq",
                    models.BigIntegerField(
                        help_text="Client sequence number for idempotency"
                    ),
                ),
                (
                    "server_tick",
                    models.BigIntegerField(
                        help_text="Server timestamp in milliseconds"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="move_history",
                        to="game.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["game", "created_at"],
                        name="game_move_game_id_c26b34_idx",
                    )
                ],
                "unique_together": {("game", "player", "client_seq")},
            },
        ),
    ]
