# Generated by Django 5.2.7 on 2025-10-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        # Rename the field in the database
        migrations.RenameField(
            model_name="game",
            old_name="game_id",
            new_name="game_code",
        ),
        # Add db_index to match the new model definition
        migrations.AlterField(
            model_name="game",
            name="game_code",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
