# Generated by Django 6.0.1 on 2026-05-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='undo_state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
