# Generated by Django 5.2.7 on 2025-10-28 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_rename_game_id_to_game_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="gameplayer",
            options={"ordering": ["game", "order"]},
        ),
        migrations.AlterModelOptions(
            name="move",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="game",
            name="turn_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games_they_play",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gameplayer",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="game.game",
            ),
        ),
        migrations.AlterField(
            model_name="gameplayer",
            name="order",
            field=models.PositiveSmallIntegerField(
                help_text="Turn order (0=first, 1=second, etc.)"
            ),
        ),
        migrations.AlterField(
            model_name="gameplayer",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="move",
            name="client_seq",
            field=models.BigIntegerField(
                help_text="Client sequence number for idempotency"
            ),
        ),
        migrations.AlterField(
            model_name="move",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="move_history",
                to="game.game",
            ),
        ),
        migrations.AlterField(
            model_name="move",
            name="payload",
            field=models.JSONField(help_text="Move payload from client"),
        ),
        migrations.AlterField(
            model_name="move",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="move",
            name="server_tick",
            field=models.BigIntegerField(help_text="Server timestamp in milliseconds"),
        ),
    ]
