# Generated by Django 6.0.1 on 2026-09-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_initial_field_savedmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='picked_map_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='picked_map_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
