"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# =============================================================================
# PRODUCTION SECURITY REQUIREMENTS
# =============================================================================
# Before deploying to production, you MUST set these environment variables:
#   - DJANGO_SECRET_KEY: A unique, unpredictable secret key (use: python -c "import secrets; print(secrets.token_urlsafe(50))")
#   - JWT_SECRET_KEY: A separate secret for JWT tokens (can be same as DJANGO_SECRET_KEY)
#   - ALLOWED_HOSTS: Comma-separated list of valid hostnames (e.g., "yourdomain.com,api.yourdomain.com")
#   - CORS_ALLOWED_ORIGINS: Frontend URLs (e.g., "https://yourdomain.com")
#   - CSRF_TRUSTED_ORIGINS: Same as CORS_ALLOWED_ORIGINS for CSRF protection
#
# The default values below are ONLY for local development convenience.
# Using defaults in production is a CRITICAL SECURITY VULNERABILITY.
# =============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY", "django-insecure-=m!dtx2tnzu5ol!r)t@&#kki*u+x!s54ny24msfj_#w5=-6md9"
)
JWT_SECRET_KEY = os.environ.get("JWT_SECRET_KEY", SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"
print(f"DEBUG: {DEBUG}")

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")
print(f"ALLOWED_HOSTS: {ALLOWED_HOSTS}")

# CORS
cors_origins = os.environ.get("CORS_ALLOWED_ORIGINS", "")
CORS_ALLOWED_ORIGINS = (
    [origin.strip() for origin in cors_origins.split(",") if origin.strip()] if cors_origins else []
)
csrf_origins = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = (
    [origin.strip() for origin in csrf_origins.split(",") if origin.strip()] if csrf_origins else []
)

# In debug mode with no CORS origins set, allow common local dev origins
if DEBUG and not CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]
    CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()
    # Allow any local network IP address (192.168.x.x, 10.x.x.x, 172.16-31.x.x) on common dev ports
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://192\.168\.\d+\.\d+:5173$",
        r"^http://192\.168\.\d+\.\d+:3000$",
        r"^http://10\.\d+\.\d+\.\d+:5173$",
        r"^http://10\.\d+\.\d+\.\d+:3000$",
        r"^http://172\.(1[6-9]|2[0-9]|3[0-1])\.\d+\.\d+:5173$",
        r"^http://172\.(1[6-9]|2[0-9]|3[0-1])\.\d+\.\d+:3000$",
    ]
else:
    CORS_ALLOWED_ORIGIN_REGEXES = []

print(f"CORS_ALLOWED_ORIGINS: {CORS_ALLOWED_ORIGINS}")
print(f"CSRF_TRUSTED_ORIGINS: {CSRF_TRUSTED_ORIGINS}")
if DEBUG:
    print(f"CORS_ALLOWED_ORIGIN_REGEXES: {CORS_ALLOWED_ORIGIN_REGEXES}")
CORS_ALLOW_CREDENTIALS = False  # Not needed for JWT-only auth (no cookies)
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CSRF_COOKIE_HTTPONLY = False  # so SPA can read cookie (or keep True and echo via meta tag)
CSRF_COOKIE_SAMESITE = (
    "None" if not DEBUG else "Lax"
)  # "None" required for cross-origin with credentials
CSRF_COOKIE_SECURE = not DEBUG  # Required when SameSite=None
CSRF_COOKIE_DOMAIN = None  # Let Django set domain automatically

# Session cookie settings - kept for Django admin only
# Our API uses JWT-only authentication (no session cookies)
# Sessions are only used by Django admin interface
SESSION_COOKIE_SAMESITE = "Lax"  # Lax is fine for admin (same-origin)
SESSION_COOKIE_SECURE = not DEBUG  # Required in production
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_HTTPONLY = True  # Security: prevent JavaScript access
SESSION_COOKIE_AGE = 86400 * 7  # 7 days
SESSION_SAVE_EVERY_REQUEST = False  # Not needed for admin
SESSION_COOKIE_PATH = "/"
SESSION_COOKIE_NAME = "sessionid"
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "channels",
    "game",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR.parent / "frontend"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "server.wsgi.application"
ASGI_APPLICATION = "server.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

db_url = os.environ.get("DATABASE_URL")
if db_url:
    DATABASES = {
        "default": dj_database_url.parse(
            db_url,
            conn_max_age=600,
            ssl_require=not DEBUG,  # SSL required in production, optional in dev
        )
    }
else:
    # Fallback for build-time / dev without DATABASE_URL
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(BASE_DIR / "db.sqlite3"),  # Convert Path to str for type checking
        }
    }

redis_url = os.environ.get("REDIS_URL")
if redis_url:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [redis_url],
            },
        }
    }
else:
    # In-memory layer for build / local dev without Redis
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # where collectstatic will put files
STATICFILES_DIRS = [BASE_DIR / "static"]  # (optional) your own extra static dir
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Logging configuration
# Set LOG_LEVEL environment variable to control logging (DEBUG, INFO, WARNING, ERROR, CRITICAL)
# Default: DEBUG in development, INFO in production
LOG_LEVEL = os.environ.get("LOG_LEVEL", "DEBUG" if DEBUG else "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        # Optional: Add file handler for production
        # "file": {
        #     "class": "logging.handlers.RotatingFileHandler",
        #     "filename": BASE_DIR / "logs" / "django.log",
        #     "maxBytes": 1024 * 1024 * 5,  # 5 MB
        #     "backupCount": 5,
        #     "formatter": "verbose",
        # },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "game": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        # Reduce noise from third-party libraries
        "channels": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}
