from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Game(models.Model):
    # id is auto-generated by Django
    STATUS = [
        ("ready", "Ready"),
        ("playing", "Playing"),
        ("ended", "Ended"),
    ]
    # Business identifier used in URLs and API
    game_code = models.CharField(max_length=20, unique=True, db_index=True)
    status = models.CharField(max_length=20, choices=STATUS, default="ready")
    settings = models.JSONField(default=dict)  # initial settings
    field = models.JSONField(default=dict)  # The game field/grid with all units, buildings, etc.
    # Frozen copy of `field` at the moment status transitions ready→playing.
    # Survives mid-game mutations so a "save as map" action always emits the
    # same starting state regardless of how far the game has progressed.
    # None for games created before this feature shipped; the save flow
    # rejects gracefully in that case.
    initial_field = models.JSONField(null=True, blank=True)
    # Optional: store whose turn
    turn_player = models.ForeignKey(
        User, null=True, blank=True, on_delete=models.SET_NULL, related_name="games_they_play"
    )
    # Pending undo state (reset at turn end). Owned by game.services.undo_state;
    # see that module for the JSON schema. None means "no undo pending".
    undo_state = models.JSONField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"Game {self.game_code}"

    def to_dict(self):
        """Serialize game with players for API responses."""
        return {
            "gameCode": self.game_code,
            "status": self.status,
            "settings": self.settings,
            "field": self.field,
            "turnPlayer": self.turn_player.username if self.turn_player else None,
            "players": [
                {
                    "id": gp.player.id,
                    "username": gp.player.username,
                    "order": gp.order,
                }
                for gp in self.players.select_related("player").order_by("order")
            ],
        }


class GamePlayer(models.Model):
    """Links players to games with their turn order."""

    game = models.ForeignKey(Game, on_delete=models.CASCADE, related_name="players")
    player = models.ForeignKey(User, on_delete=models.CASCADE, related_name="game_memberships")
    order = models.PositiveSmallIntegerField(help_text="Turn order (0=first, 1=second, etc.)")
    scout_revealed_coords = models.JSONField(
        default=list,
        help_text="List of coordinates revealed by scout actions this turn, format: [[x1, y1], [x2, y2], ...]",
    )

    class Meta:
        unique_together = [("game", "player")]
        constraints = [models.UniqueConstraint(fields=["game", "order"], name="unique_game_order")]
        ordering = ["game", "order"]

    def __str__(self):
        return f"{self.player} in Game {self.game.game_code} (order {self.order})"


class SavedMap(models.Model):
    """A canonical Map JSON saved by a user. Used by the multiplayer
    "Save map" action and the lobby's "Load Map" picker.

    ``data`` holds the full v1 canonical Map document (see
    ``services/map_snapshot.py``). The denormalised columns at the
    side are populated from metadata for quick listing/filtering.
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="saved_maps")
    name = models.CharField(max_length=120)
    data = models.JSONField()
    players_num = models.PositiveSmallIntegerField()
    width = models.PositiveSmallIntegerField()
    height = models.PositiveSmallIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = [("user", "name")]
        ordering = ["-created_at"]

    def __str__(self):
        return f"SavedMap {self.name} by {self.user}"


class Move(models.Model):
    """Records every move with idempotency check via client_seq."""

    game = models.ForeignKey(Game, on_delete=models.CASCADE, related_name="move_history")
    player = models.ForeignKey(User, on_delete=models.CASCADE, related_name="moves")
    payload = models.JSONField(help_text="Move payload from client")
    client_seq = models.BigIntegerField(help_text="Client sequence number for idempotency")
    server_tick = models.BigIntegerField(help_text="Server timestamp in milliseconds")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = [("game", "player", "client_seq")]
        indexes = [
            models.Index(fields=["game", "created_at"]),
        ]
        ordering = ["-created_at"]

    def __str__(self):
        return f"Move {self.client_seq} by {self.player} in Game {self.game.game_code}"
